iberia:
  bbox:
    min_lat: 35.7
    min_lon: -9.9
    max_lat: 44.1
    max_lon: 4.5
italy:
  bbox:
    min_lat: 36.5
    min_lon: 6.7
    max_lat: 47.3
    max_lon: 18.6
poland:
  bbox:
    min_lat: 48.8
    min_lon: 13.9
    max_lat: 54.9
    max_lon: 24.3