""" 
This scripts converts the netcdf generated by `cams_cut_region.py` to a folder with .tiff files
"""
import os

import numpy as np
import xarray as xr
from PIL import Image

region = "iberia"
variable = "no2"

#file = f"/home/urbanaq/data/cams/{variable}/{variable}_{region}.nc"
file = f"/home/urbanaq/data/cams/2024/cams_{region}.nc"
output_folder = f"/data1/data_prep/cams_forecast/{variable}/{region}"

os.makedirs(output_folder, exist_ok=True)

xds = xr.open_dataset(file)
# Save coordinates as separate .tiff files
Image.fromarray((xds['latitude'].values).astype(np.float32)).save(f"{output_folder}/lat.tiff")
Image.fromarray((xds['longitude'].values).astype(np.float32)).save(f"{output_folder}/lon.tiff")

# Save each time step as a separate .tiff file
for time in xds.time:
    data = xds[variable].sel(time=time).values
    filename = time.values.astype(str).replace(":", "-").replace("T", "_").split(".")[0]
    Image.fromarray((data).astype(np.float32)).save(f"{output_folder}/{filename}.tiff")
